language: python

python:
  - "3.5"

install:
- pip install -r requirements.txt

script:
- coverage run --rcfile=.coveragerc manage.py test parser reports
- coverage report --rcfile=.coveragerc
- flake8 .

after_success:
  - coveralls -c .coveragerc
