# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=8)),
                ('emp_number', models.CharField(max_length=100)),
                ('emp_type', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
            ],
        ),
    ]
